executors:
  latest-image:
    machine:
      image: ubuntu-2004:202010-01
jobs:
  build:
    environment:
      BUILDX_NO_DEFAULT_LOAD: 1
    executor: latest-image
    steps:
      - checkout
      - command: ./install-binfmt-platforms.sh
        name: Install binfmt Platforms
        run: null
      - command: ./build-multiarch.sh
        name: Build
        run: null
  deploy:
    environment:
      PUSH: --push
    executor: latest-image
    steps:
      - command: docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
        name: Login to Docker Hub
        run: null
      - checkout
      - command: ./install-binfmt-platforms.sh
        name: Install binfmt Platforms
        run: null
      - command: ./build-multiarch.sh
        name: Build & Push
        run: null
version: 2.1
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - /.*-ci/
      - deploy:
          filters:
            branches:
              only:
                - main
                - master
  version: 2.1
